backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "events"
    label: "Events"
    folder: "src/pages/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "event-post"}
      - {label: "Title", name: title, widget: string}
      - {label: "Google Drive Link", name: googleDriveLink, widget: string}
      - {label: "Image", name: image, widget: image}
      - {label: "Publish Date", name: "date", widget: "datetime"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Index Page"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Hero Section", name: heroSection, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: "Hero Image", name: heroImage, widget: image}]}
          - {label: "Next Event Section", name: nextEventSection, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Date, name: date, widget: date, format: "MMM Do YY"},{label: "Location Name", name: locationName, widget: string},{label: "Location Address", name: locationAddress, widget: string}, {label: "RSVP Link", name: rsvpLink, widget: string}]}
          - {label: "Agenda Section", name: agendaSection, widget: object, fields: [{label: Active, name: active, widget: boolean, default: false}, {label: "Agenda Items", name: agendaItems, widget: list, fields: [{label: "Time Range", name: timeRange, widget: string}, {label: Title, name: title, widget: string}, {label: AgendaDescription, name: agendaDescription, widget: string}]}]}
          - {label: "Panelist Section", name: panelistSection, widget: object, fields: [{label: Active, name: active, widget: boolean, default: false}, {label: "Panelist Items", name: panelistItems, widget: list, fields: [{label: Image, name: image, widget: image},{label: Name, name: name, widget: string,}, {label: Position, name: position, widget: string}, {label: Biography, name: biography, widget: markdown}]}]}
          - {label: "Location Section", name: locationSection, widget: object, fields: [{label: Date, name: date, widget: date, format: "MMM Do YY"}, {label: "Event Time Range", name: eventTimeRange, widget: string, default: "7:00PM - 9:00PM"}, {label: "Venue Name", name: venueName, widget: string}, {label: "Venue Address", name: venueAddress, widget: string},{label: Coordinates, name: coordinates, widget: object, fields: [{label: Latitude, name: latitude, widget: string}, {label: Longitude, name: longitude, widget: string}]}, {label: "RSVP Link", name: rsvpLink, widget: string}, {label: "Parking Blurb", name: parkingBlurb, widget: markdown, required: false}]}
      - file: "src/pages/about/index.md"
        label: "About Page"
        name: "About Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Hero Section", name: heroSection, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: "Hero Image", name: heroImage, widget: image}]}
          - {label: "About Section Extended", name: aboutSectionExtended, widget: markdown}
          - {label: "Board of Directors Section", name: boardOfDirectorsSection, widget: list, fields: [{label: "Name", name: name, widget: string}, {label: "Position", name: position, widget: string}]}
      - file: "src/pages/sponsorship/index.md"
        label: "Sponsorship Page"
        name: "Sponsorship Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "sponsorship-page"}
          - {label: "Hero Section", name: heroSection, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: "Hero Image", name: heroImage, widget: image}]}
          - {label: "Sponsors Section", name: sponsorsSection, widget: list, fields: [{label: "Sponsor", name: sponsor, widget: string}, {label: "Logo", name: logo, widget: image}, {label: "Website", name: website, widget: string}]}
      - file: "src/pages/contact/index.md"
        label: "Contact Page"
        name: "Contact Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Hero Section", name: heroSection, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text, required: false}, {label: "Hero Image", name: heroImage, widget: image}]}
